### ISSUE TITLE
A recommedation

### ISSUE THREAD

**Issue by bumsteed-dev** [mikemcbride/vscode-electron-highlighter#6]
Hello! I love your theme, but I have a question, is there a way to make it Italic the theme?

**Comment by mikemcbride** [comment]
Hey! So glad you enjoy the theme, thank you! If there are specific things you'd like to be italicized, I think you can go into your settings.json file and override them. I add italics in a few places, such as comments. Here's an example of how you would add that in your own settings.json file:

```json
    "editor.tokenColorCustomizations": {
        "comments": {
            "fontStyle": "italic"
        }
    },
```

VS Code should autocomplete suggestions for you to help figure out what properties you can modify!

**Comment by bumsteed-dev** [comment]
Oh thanks man!
